### PR TITLE
Resolved issues - #17 & #18

### LINKED ISSUE #17: Make input fields to take specific input types
**Describe the bug**
Fields are accepting all type of values.

**To Reproduce**
1. Go to Input Fields
2. Try entering text in phone number or weight fields
3. See error

**Expected behavior**
These fields should only take specific type of input

**Screenshots**

 

**Smartphone (please complete the following information):**

|               | |
|---------------|-|
|Device         | Redmi Note 4 |
|Android Version| Nougat 7.0  |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:  Open to all

### PR DESCRIPTION
**Pull request by h4rz**
Fixes #17, #18 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/blob/master/CONTRIBUTING.md) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 
- For issue #17 
   - Added mobile number verification
   - Added inputType for name, email, age and mobile

- For issue #18 
   - Added spinner for gender and blood group

Screenshots for the change:
image

image

### CODE REVIEW

**Review by dheerajkotwani — APPROVED** [review]

**Review by plazzy99 — APPROVED** [review]
@h4rz your code LGTM

```You should always create 1 pr for a single issue```

**Comment by h4rz** [comment]
> @h4rz your code LGTM
> 
> ```You should always create 1 pr for a single issue```
> 

I was thinking of doing that but as both the issues were related and to avoid any conflicts I created a single PR.

**Comment by plazzy99** [comment]
> > @h4rz your code LGTM
> > `You should always create 1 pr for a single issue`
> 
> I was thinking of doing that but as both the issues were related and to avoid any conflicts I created a single PR.

Go through the readme of plasma Donor everything is clearly mentioned to avoid conflict in you pr.

**Comment by h4rz** [comment]
@plazzy99 sure will check it. Could you also add the hacktoberfest-accepted label to this PR?

**Pull request merged**
