### PR TITLE
Implement Github Actions

### LINKED ISSUE #50: Setup Github Actions to ensure that new features won't break anything in the codebase
**Is your feature request related to a problem? Please describe.**
Now we might probably merge Pull Requests without test whether it works as expected and don't break anything in the current codebase. Instead of a manual check, we can automate this flow. If a new PR passes all steps, then it means to be merged.

**Describe the solution you'd like**
To set up, a Github Actions CI

**Describe alternatives you've considered**
No alternative to a CI pipeline

**Additional context**

### PR DESCRIPTION
**Pull request by nuhkoca**
Closes #50 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/blob/master/CONTRIBUTING.md) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes:

This PR adds a CI pipeline for the project in order to ensure that new changes comply with standards and won't break anything. The workflow is going to be triggered in the event of PRs against the master branch and merge on the master branch. To make sure that your branch doesn't break anything please execute the Gradle script below:

```gradle
./gradlew lintDebug ktlintCheck detekt testDebugUnitTest
```

Can you check if Actions is enabled for the repository?

### CODE REVIEW

**Review by dheerajkotwani — APPROVED** [review]

**Review by dheerajkotwani — APPROVED** [review]

**Review by plazzy99 — APPROVED** [review]

**Comment by dheerajkotwani** [comment]
@nuhkoca is it completed or are you still left with changes?

**Comment by nuhkoca** [comment]
@dheerajkotwani sorry I just reverted the last commit. Did you give it a try to see Actions can be set up for this repository? I couldn't see any option in `Actions` tab. Can you help me?

**Comment by nuhkoca** [comment]
@dheerajkotwani @plazzy99 any update?

**Review by dheerajkotwani — APPROVED** [review]

**Comment by dheerajkotwani** [comment]
Great work @nuhkoca Actions are working properly😀😀

**Comment by nuhkoca** [comment]
@dheerajkotwani you are welcome, great to see it is working, now master is safer :D

**Pull request merged**
