### PR TITLE
Issue #64 : Add error checks for signup

### LINKED ISSUE #64: Not all input field errors are shown while signing up.
**Describe the bug**
Not all input field errors are shown while signing up.

**To Reproduce**
1. Go to Sign up screen.
2. Click on Sign up without entering anything.
3. Input field error is shown only for Email while all the fields are empty.

**Expected behavior**
Input field errors should be shown for all faulty fields. 

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by ardlank**
Fixes #64 : Add error checks for signup

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/blob/master/CONTRIBUTING.md) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by ardlank** [comment]
Screenshot:

**Comment by ardlank** [comment]
Screenshot:
Screenshot_1602452717

**Review by dheerajkotwani — CHANGES_REQUESTED** [review]
@ardlank while creating a PR if you add issue number followed by a '#' in the PR title that will automatically link to the issue you are solving and will be good for your open source practicing too. Kindly change the PR message accordingly.

**Comment by ardlank** [comment]
> @ardlank while creating a PR if you add issue number followed by a '#' in the PR title that will automatically link to the issue you are solving and will be good for your open source practicing too. Kindly change the PR message accordingly.

@dheerajkotwani done

**Review by dheerajkotwani — APPROVED** [review]

**Pull request merged**
