### PR TITLE
Feature EditProfile 

### LINKED ISSUE #69: Edit Profile not showing the saved data from the servers.
**Describe the bug**
Edit Profile not showing the saved data from the servers.

**To Reproduce**
1. Go to Profile Section.
2. Click on Edit Profile
4. See bug

**Expected behavior**
While opening the edit profile screen the data is not showing that is saved on the server.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open to all

### PR DESCRIPTION
**Pull request by lingarajsankaravelu**
Fixes #69 ,#59
Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/blob/master/CONTRIBUTING.md) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Note: 
Tried  resolving conflict from my end with upstream and unsuccessful. 

Changes: 
1.  In editProfile, Moved all raw Hint text to String resources, added actionId for all Edittext.
2.  Added oneway databinding for profile and editProfile screen. 
3. Complete Implementation of EditProfile with FireBase. 
4. Renamed directories (Model to models, Interface to interfaces)

### CODE REVIEW

**Comment by dheerajkotwani** [comment]
@lingarajsankaravelu can you please add a short gif file in your PR comment showing the contents in EditProfile when user opens it also data being displayed in Profile Section when its saved.

**Comment by dheerajkotwani** [comment]
Also remove the merge conflicts.

**Comment by lingarajsankaravelu** [comment]
@dheerajkotwani sure

**Comment by lingarajsankaravelu** [comment]
edit_profile_mi_gf

**Comment by nuhkoca** [comment]
@lingarajsankaravelu as it seems you did a wrong merge. I still see the old definitions like `activity!!` instead of `requireActivity()`.

**Comment by lingarajsankaravelu** [comment]
It was the right merge @nuhkoca , It has activity!! in one place, is that what u r referring to as well  or did I miss something?

**Comment by nuhkoca** [comment]
@lingarajsankaravelu okay, I just checked your build result, that's why I said. Can you fix and push again? As you might realize, CI has failed. Thanks.

**Comment by lingarajsankaravelu** [comment]
> @lingarajsankaravelu okay, I just checked your build result, that's why I said. Can you fix and push again? As you might realize, CI has failed. Thanks.
 working on it. As the lint, Klint and Detekt were added  to the CI pipeline recently . Running and fixing all these things in my for the whole project to be frank. So that my commit can pass the CI.

**Comment by nuhkoca** [comment]
@lingarajsankaravelu you can just run this Gradle command: `/gradlew lintDebug ktlintFormat detekt testDebugUnitTest`

**Review by plazzy99 — APPROVED** [review]
👍🏻

**Pull request merged**
