### PR TITLE
Bottom navigation bar added

### LINKED ISSUE #121: Adding Bottom Navigation Bar
Sir, I want to add the **bottom navigation bar**.
bottom navigation bar
Sir, please assign me this issue.

### PR DESCRIPTION
**Pull request by sitamadex11**
Fixes #121 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/blob/master/CONTRIBUTING.md) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

## Changes:
I have added the bottom navigation bar  

https://user-images.githubusercontent.com/76570320/117416466-095bb800-af37-11eb-96ac-a7bbbfd78fb7.mp4

### CODE REVIEW

**Review by dheerajkotwani — CHANGES_REQUESTED** [review]
image
The UI and fonts should be more similar to this

**Comment by sitamadex11** [comment]
Ok I will update it as soon as possible

**Comment by sitamadex11** [comment]
## Updated UI
https://user-images.githubusercontent.com/76570320/117452619-9b78b600-af61-11eb-9281-3901b6082150.mp4

**Review by dheerajkotwani — APPROVED** [review]

**Comment by sitamadex11** [comment]
@dheerajkotwani @dhruv-1001 vaiya please add a level tag

**Pull request merged**
