### PR TITLE
Added lottie files for increasing splash screen interactivity.

### PR DESCRIPTION
**Pull request by hemant2705**
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/blob/master/CONTRIBUTING.md) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by dheerajkotwani** [comment]
@hemant2705 do add the screen shot for the changes.

**Comment by hemant2705** [comment]
ss2
splashscreen

**Comment by hemant2705** [comment]
Can anyone review it please and tell the status?

**Comment by hemant2705** [comment]
Can you please add the level tag in this one sir

**Pull request merged**
